### PR TITLE
Typo and Grammar fixes in README.md

### PR DESCRIPTION
**Pull request by alundiak**

### CODE REVIEW

**Comment by alundiak** [comment]
up :)

**Review by angeloocana — APPROVED** [review]
Awesome!

**Comment by alundiak** [comment]
Ou, but my PR not to the correct fork... OMG. so much forks....

**Comment by alundiak** [comment]
or not? @thebergamo  will u merge?

**Comment by thebergamo** [comment]
Thanks @alundiak

**Pull request merged**
